version: '3.7'
services:

  customer-db:
    container_name: customer-db
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=customer-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  item-db:
    container_name: item-db
    image: 'postgres:15'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=item-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  pgadmin:
    container_name: pgadmin-shopping
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  redis:
    container_name: redis
    image: redis:7.0.5
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch_springboot
    environment:
      - bootstrap.memory_lock
      - ES_JAVA_OPTS
      - discovery.type
      - xpack.security.enabled
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana_springboot
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL
      - ELASTICSEARCH_HOSTS
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:8.3.3
    container_name: logstash_springboot
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      - LS_JAVA_OPTS
    networks:
      - elastic
    depends_on:
      - elasticsearch

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED

networks:
  elastic:
    driver: bridge

volumes:
  db_data:

  elasticsearch_data:
    driver: local
